# Copyright (C) 2021 Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Copyright (C) 2013-2019 Nicolas Lamirault <nicolas.lamirault@gmail.com>

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Install | X utilities
  community.general.pacman:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - libglvnd
      - xorg-server
      - xorg-xinit
      - arandr
      - slim
      - slim-themes
      - archlinux-themes-slim
      # - lxdm
      # - lxdm-gtk3
      - sddm
      - lightdm
      - lightdm-gtk-greeter-settings
      - lightdm-webkit2-greeter
      - lightdm-webkit-theme-litarvan
      - light-locker
      - clipmenu
      - clipnotify

# - name: Install web browsers (with Yay)
#   kewlfft.aur.aur:
#     name: "{{ packages }}"
#     use: makepkg
#     state: present
#   become: yes
#   become_user: aur_builder
#   vars:
#     packages:
#       - google-chrome-beta
#       # - brave

- name: Install | Graphics applications
  community.general.pacman:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - gimp
      - inkscape
      - flameshot

- name: Install | Video applications
  community.general.pacman:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - vlc

- name: Install | Music applications
  community.general.pacman:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - pulseaudio
      - pavucontrol
      - pulsemixer
      - playerctl

# - name: Install music applications with Yay
#   community.general.pacman:
#     name: "{{ packages }}"
#     state: present
#     executable: yay
#     # extra_args: --builddir /var/cache/yay
#   vars:
#     packages:
#       - spotify

- name: Install | Communications applications
  community.general.pacman:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - irssi
      - vinagre
      - rdesktop

# - name: Install communications applications with Yay
#   community.general.pacman:
#     name: "{{ packages }}"
#     state: present
#     executable: yay
#     # extra_args: --builddir /var/cache/yay
#   vars:
#     packages:
#       - slack-desktop
#       - zoom

- name: Install | Documentation applications
  community.general.pacman:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - evince
      - mupdf

- name: Install | Fonts
  community.general.pacman:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - awesome-terminal-fonts
      # - ttf-symbola

# - name: Install fonts with Yay
#   community.general.pacman:
#     name: "{{ packages }}"
#     state: present
#     executable: yay
#     # extra_args: --builddir /var/cache/yay
#   vars:
#     packages:
#       - nerd-fonts-hack

- name: Install | Security tools
  community.general.pacman:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - openvpn
      - wireguard-tools
      - keepassxc
      - arch-audit

- name: Install | Torrent tools
  community.general.pacman:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - deluge
      - fragments
      - transmission-gtk
      - transmission-cli

# - name: Install cloud development tools with Yay
#   community.general.pacman:
#     name: "{{ packages }}"
#     state: present
#     executable: yay
#     # extra_args: --builddir /var/cache/yay
#   vars:
#     packages:
#       - direnv-bin
#       - tfenv
#       - tgenv

# - name: Install network tools with Yay
#   community.general.pacman:
#     name: "{{ packages }}"
#     state: present
#     executable: yay
#     # extra_args: --builddir /var/cache/yay
#   vars:
#     packages:
#       - iwtk

- name: Install | Bluetooth tools
  community.general.pacman:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - bluez
      - bluez-utils
      - bluez-tools
      - blueman
      - gnome-bluetooth
  notify:
    - Bluetooth service

- name: System | Bluetooth service
  ansible.builtin.systemd:
    state: started
    daemon_reload: true
    name: bluetooth
